language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode9
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then eval "$(curl -sL https://raw.githubusercontent.com/ryuichis/oclint-cpp-travis-ci-examples/master/oclint-ci-install.sh)"; fi
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - make
  - ./bin/test-countly ${COUNTLY_HOST} ${COUNTLY_APP_KEY}
  - cd ..
  - cp build/compile_commands.json .
  - oclint-json-compilation-database
